// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCaJ1_8_0xqxkKcVzpxgZ9XUw_igi09og',
    appId: '1:554273373145:web:88fe3c03c76abf64a2f7c8',
    messagingSenderId: '554273373145',
    projectId: 'voca-33a1c',
    authDomain: 'voca-33a1c.firebaseapp.com',
    storageBucket: 'voca-33a1c.firebasestorage.app',
    measurementId: 'G-N55NJ24SE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcio3I2D44ofIXpnniDN9QQY6mKtR7GNk',
    appId: '1:554273373145:android:b2b5ed369ed010bda2f7c8',
    messagingSenderId: '554273373145',
    projectId: 'voca-33a1c',
    storageBucket: 'voca-33a1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtKKS_ZXNyIux13vmWaVqR79mKveGbnvc',
    appId: '1:554273373145:ios:136abcfe7a6ec10ca2f7c8',
    messagingSenderId: '554273373145',
    projectId: 'voca-33a1c',
    storageBucket: 'voca-33a1c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtKKS_ZXNyIux13vmWaVqR79mKveGbnvc',
    appId: '1:554273373145:ios:136abcfe7a6ec10ca2f7c8',
    messagingSenderId: '554273373145',
    projectId: 'voca-33a1c',
    storageBucket: 'voca-33a1c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCaJ1_8_0xqxkKcVzpxgZ9XUw_igi09og',
    appId: '1:554273373145:web:65ad518f27a9b4b8a2f7c8',
    messagingSenderId: '554273373145',
    projectId: 'voca-33a1c',
    authDomain: 'voca-33a1c.firebaseapp.com',
    storageBucket: 'voca-33a1c.firebasestorage.app',
    measurementId: 'G-BK7ZBZ54MH',
  );

}